#!/usr/bin/env bash
# This script: Creates a PID file with its PID
# - Displays messages when receiving SIGTERM and SIGINT signals
# - Deletes the PID file and terminates on SIGQUIT or SIGTERM

# Function to clean up and exit
cleanup_and_exit() {
	rm -f /var/run/myscript.pid
	exit 0
}

echo "$$" > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely, sleep and delete
while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && cleanup_and_exit' SIGTERM
	trap 'cleanup_and_exit' SIGQUIT
done
