#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# Has 2-second delay between each iteration.
# Responds to SIGTERM with "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
